---
- name: Install Podman on Rocky Linux 8
  hosts: all
  become: true

  tasks:
    - name: Ensure system is up to date
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Podman
      dnf:
        name: podman

